language: go
go:
  - 1.8.x
env:
  - GOOS=linux
script:
  - go build -o tickerdumper -v main.go
  - pwd
  - find *
deploy:
  provider: releases
  api_key:
    secure: KEeZUUpt8LqJyPQ3+pi8Yd0CrUqlbin62xpMRexmXeg4KqkDZDiC3A1jwYG7eE3uW7pKAKERe+zBT5YCNT6OZ/S8Cve0PN+t4rb47yuBoeFLXffHa8X+GJCbPSD1aMunh75iGV5KVjbmGxyR0HysBR7ql+93q8U/vL5TDnMqhf2vP4GNX07Pq9L/6WPONrq4qb9RshLW5pmUV/VS/gdcuEddaoDs1mEw5IX1vUP0v3s8QUcxWKem4axPwiAAiywGj+u5d5bD0Tl3EQo45PlZKcv/aBz0VEHDvVfeawHrgilUuuP3rH9SA+8K6qhtB54KgWVOyLSptHjELnU8k0qlZWwSr/anvXfAeVzxtspKimQEC5Khf6WpHS8gd/+TN1SVipNmdFfNruufNcue7RD49ggitSvou89viI2XAUJnaqonLKTixSOXNpI2lZVriyjdb8YDSodCZKF0t6/wEe8XYl+aBV0+fiIku4kvAoW1Ek5da2y6DM4MMG9O/P9LVMKtc6Z+0Ho+iDJNgaOIaBBLvalNTPhpPpNk3e00QeCanK7v6SAfaxDwz9DQU2k86vrbYixxFgaScA881c0cqte82/aDuEe4huhdRg0fnWoDvb6ESUlCq9yxA/OGyeKMiDBcOVU70xO/lqG0UfMgkudwIa4QTfFgJE1igL42phxW3BA=
  file: tickerdumper
  on:
    tags: true
  skip_cleanup: true
